In [2]:
# Week 7 Exercise: Matrix operations and image processing

# I start by importing the libraries I need
import numpy as np
import cv2
import matplotlib.pyplot as plt

# These are the matrices given in the exercise. I just enter them as NumPy arrays.
A = np.array([
    [10, -1, 2, -3],
    [5, 1, -1, 4],
    [9, 4, 6, -2]
])

B = np.array([
    [1, -2, 3, 7],
    [0, 1, -3, -2],
    [2, 1, 1, 4]
])

C = np.array([
    [4, 0, -2, 3],
    [3, 6, 9, 7],
    [2, 2, 5, 1]
])

# Now I check the shape of each matrix to make sure they're compatible for operations
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)
print("Shape of C:", C.shape)

# Trying to add A and B (same shapes, so it should work)
print("\nA + B:")
print(A + B)

# Matrix multiplication A @ B (this works because A is 3x4 and B is 3x4, so this will give an error)
try:
    print("\nA @ B:")
    print(A @ B)
except:
    print("A @ B is not defined because their shapes don't match for matrix multiplication.")

# Matrix multiplication A @ C (should be valid: 3x4 and 3x4 won't work, this is to test)
try:
    print("\nA @ C:")
    print(A @ C)
except:
    print("A @ C is not defined either.")

# Transpose of matrix C
print("\nTranspose of C:")
print(C.T)

# Testing the transpose rule: (A + B)^T = A^T + B^T
print("\nCheck if (A + B)^T == A^T + B^T:")
print(np.array_equal((A + B).T, A.T + B.T))

# Testing the transpose rule: (AC)^T = C^T A^T (will give error if AC is not valid)
try:
    AC = A @ C
    print("\nCheck if (AC)^T == C^T A^T:")
    print(np.array_equal(AC.T, C.T @ A.T))
except:
    print("Cannot test (AC)^T = C^T A^T because A @ C is not defined.")

# Trying to find the inverse of matrix C
try:
    C_inv = np.linalg.inv(C)
    print("\nInverse of C:")
    print(C_inv)
except:
    print("Matrix C is not invertible.")

# Now for the image part — I load and display the image given in the assignment
img = cv2.imread("week7 image.jpg")

if img is not None:
    # OpenCV loads images in BGR, but matplotlib needs RGB, so I convert it
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Showing the image
    plt.imshow(img_rgb)
    plt.axis('off')
    plt.title("Week 7 Image")
    plt.show()

    # Print out the image shape (dimensions)
    print("\nImage shape:", img.shape)
    print("The third number means there are 3 color channels (Red, Green, Blue)")
else:
    print("Image file not found. Make sure 'week7 image.jpg' is in the same folder as this notebook.")


Shape of A: (3, 4)
Shape of B: (3, 4)
Shape of C: (3, 4)

A + B:
[[11 -3  5  4]
 [ 5  2 -4  2]
 [11  5  7  2]]

A @ B:
A @ B is not defined because their shapes don't match for matrix multiplication.

A @ C:
A @ C is not defined either.

Transpose of C:
[[ 4  3  2]
 [ 0  6  2]
 [-2  9  5]
 [ 3  7  1]]

Check if (A + B)^T == A^T + B^T:
True
Cannot test (AC)^T = C^T A^T because A @ C is not defined.
Matrix C is not invertible.
Image file not found. Make sure 'week7 image.jpg' is in the same folder as this notebook.
